### ISSUE TITLE
Reading city forecast

### ISSUE THREAD

**Issue by Enric1Vic** [Integrated-Project-2-2024-UVic-UCC/organic-weather#26]
This is an alternative way from reading the city forecast. The telegram bot had some issues. 
From OpenWeatherMap we can call an instructions that returns the city forecast. 
From this task has two steps:

-Achieve the ESP32 call this webpage instruction

- Upon we have the answer returned, in JSON structure, do a parse for selected the wanted information.

**Comment by Enric1Vic** [comment]
Search information on how to read and publish information of city weather-forecast

**Comment by davidvega2001** [comment]
The program uses the OpenWeatherMap webpage, with a particular API key. The esp do a call for this API with the httpclient library, receive a JSON file and deserialitzes it. 
Next upgrades could be:

- In the API call to modify the lattitud and longitud in a easy way.
