### ISSUE TITLE
Alternative design for flower movement

### ISSUE THREAD

**Issue by PViedma13** [Integrated-Project-2-2024-UVic-UCC/organic-weather#35]
Because the gear system with the worm screw is not producing the results it should, it has been decided to start designing an alternative system and for now parallel to the current design:
- Parallel: because we want to do some last tests before completely discarding the current design.
- Alternative: this design does not have gears or worm screw, in short we have two pieces without taking into account the petals.
The first piece will be a central piece, one end of which will be connected to the stepper motor that will carry out the movement and the other part is where the petals will be hooked. This part will be like a crown where the petals will be placed, that is, they will fit together, allowing the petal to have complete movement. We could imagine the movement as that of a hinge. The shape is not defined.
The second piece will be both functional and visual. We can see that visually it will be a calyx of a flower and inside it will have the shape of a coap. Its function will be that when the central piece lowers, the petals, when resting on the calyx, begin to close on the inside of the cup, so when the central piece has reached its minimum, the flower is completely closed.

Visual scheme:

![Image](https://github.com/Integrated-Project-2-2024-UVic-UCC/organic-weather/assets/148632510/4168c13a-e7db-4863-88cc-9d7d0fdf96af)

**Comment by Enric1Vic** [comment]
Main stick and petals done. Working by now. Will increase the scale to fit better every piece.
