### ISSUE TITLE
Electronics Schematic Draft

### ISSUE THREAD

**Issue by PViedma13** [Integrated-Project-2-2024-UVic-UCC/organic-weather#9]
Based on the knowledge obtained from the datasheets of all the components, we can make the first draft of the electronic board of the entire mechanism, connecting all the components.

**Comment by PViedma13** [comment]
Based on the knowledge obtained from the datasheets of all the components, we can make the first draft of the electronic board of the entire mechanism, connecting all the components.

**Comment by davidvega2001** [comment]
Schematic draft done.
